// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	UserID   string `json:"username"`
	Password string `json:"password"`
}

type LoginReply struct {
	Token string `json:"token,default=''"`
	Role  string `json:"role"`
}

type RegisterReq struct {
	UserID   string `json:"username"`
	Password string `json:"password"`
	Role     string `json:"role"`
	Name     string `json:"name"`
}

type RegisterReply struct {
	Token string `json:"token,default=''"`
}

type UserInfo struct {
	Id   string `json:"id"`
	Role string `json:"role"`
	Name string `json:"name"`
}

type QueryUserReq struct {
	Id string `path:"id"`
}

type QueryUsersResp struct {
	Users []UserInfo `json:"users"`
}

type SetSecretaryReq struct {
	Id          string `json:"id"`
	IsSecretary bool   `json:"is_secretary"`
}

type VerifyTokenReq struct {
}

type VerifyTokenResp struct {
	UserId   string `json:"userId"`
	UserRole string `json:"userRole"`
	Ok       bool   `json:"ok"`
}
