// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	UserID   string `json:"username"`
	Password string `json:"password"`
}

type LoginReply struct {
	Token string `json:"token,default=''"`
	Role  string `json:"role"`
}

type RegisterReq struct {
	UserID   string `json:"username"`
	Password string `json:"password"`
	Role     string `json:"role"`
	Name     string `json:"name"`
}

type RegisterReply struct {
	Token string `json:"token,default=''"`
}
