// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"TDS-backend/student/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/student/query/all",
				Handler: QueryAllStudentsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/student/query/nondefensed",
				Handler: QueryNondefensedStudentsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/student/remove",
				Handler: RemoveStudentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/student/query/id/:id",
				Handler: QueryStudentHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
