version: '3'

networks:
  app-tier:
    driver: bridge

services:
  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    expose:
      - "2379"
      - "2380"
    networks:
      - app-tier

  user_rpc:
    container_name: user_rpc_container
    networks:
      - app-tier
    image: user_rpc:v1
    restart: always
    expose:
      - "9001"
    depends_on:
      - etcd

  excel_rpc:
    container_name: excel_rpc_container
    networks:
      - app-tier
    image: excel_rpc:v1
    restart: always
    expose:
      - "9002"
    depends_on:
      - etcd

  teacher_rpc:
    container_name: teacher_rpc_container
    networks:
      - app-tier
    image: teacher_rpc:v1
    restart: always
    expose:
      - "9003"
    depends_on:
      - etcd

  classroom_rpc:
    container_name: classroom_rpc_container
    networks:
      - app-tier
    image: classroom_rpc:v1
    restart: always
    expose:
      - "9004"
    depends_on:
      - etcd
 
  student_rpc:
    container_name: student_rpc_container
    networks:
      - app-tier
    image: student_rpc:v1
    restart: always
    expose:
      - "9005"
    depends_on:
      - etcd

  route_api:
    container_name: route_api_container
    networks:
      - app-tier
    image: route_api:v1
    restart: always
    expose:
      - "8890"
      
  user_api:
    container_name: user_api_container
    networks:
      - app-tier
    image: user_api:v1
    restart: always
    expose:
      - "8889"
    depends_on:
      - user_rpc
    
  admin_api:
    container_name: admin_api_container
    networks:
      - app-tier
    image: admin_api:v1
    restart: always
    expose:
      - "8891"
    depends_on:
      - excel_rpc
      - user_rpc

  schedule_api:
    container_name: schedule_api_container
    networks:
      - app-tier
    image: schedule_api:v1
    restart: always
    expose:
      - "8892"
    depends_on:
      - student_rpc
      - classroom_rpc
      - teacher_rpc

  teacher_api:
    container_name: teacher_api_container
    networks:
      - app-tier
    image: teacher_api:v1
    restart: always
    expose:
      - "8893"
    depends_on:
      - teacher_rpc
  
  classroom_api:
    container_name: classroom_api_container
    networks:
      - app-tier
    image: classroom_api:v1
    restart: always
    expose:
      - "8894"
    depends_on:
      - classroom_rpc

  student_api:
    container_name: student_api_container
    networks:
      - app-tier
    image: student_api:v1
    restart: always
    expose:
      - "8895"
    depends_on:
      - student_rpc

  nginx-gateway:
    image: nginx:1.21.5
    container_name: nginx-gateway
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8888:8081
    volumes:
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/log:/var/log/nginx
    networks:
      - app-tier