version: '3'

networks:
  app-tier:
    driver: bridge

services:
  mongo:
    image: mongo
    container_name: mongodb_container
    restart: always
    ports:
        - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./mongo/mongo_data:/data/db
    networks:
      - app-tier

  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    expose:
      - "2379"
      - "2380"
    networks:
      - app-tier

  user_rpc:
    build: 
      context: .
      dockerfile: ./user/cmd/rpc/Dockerfile
    container_name: user_rpc_container
    networks:
      - app-tier
    image: user_rpc:v1
    restart: always
    expose:
      - "9001"
    depends_on:
      - etcd
      - mongo

  teacher_rpc:
    build: 
      context: .
      dockerfile: ./teacher/cmd/rpc/Dockerfile
    container_name: teacher_rpc_container
    networks:
      - app-tier
    image: teacher_rpc:v1
    restart: always
    expose:
      - "9003"
    depends_on:
      - etcd
      - mongo

  classroom_rpc:
    build: 
      context: .
      dockerfile: ./classroom/cmd/rpc/Dockerfile
    container_name: classroom_rpc_container
    networks:
      - app-tier
    image: classroom_rpc:v1
    restart: always
    expose:
      - "9004"
    depends_on:
      - etcd
      - mongo
 
  student_rpc:
    build: 
      context: .
      dockerfile: ./student/cmd/rpc/Dockerfile
    container_name: student_rpc_container
    networks:
      - app-tier
    image: student_rpc:v1
    restart: always
    expose:
      - "9005"
    depends_on:
      - etcd
      - mongo

  route_api:
    build: 
      context: .
      dockerfile: ./route/cmd/api/Dockerfile
    container_name: route_api_container
    networks:
      - app-tier
    image: route_api:v1
    restart: always
    expose:
      - "8890"
    depends_on:
      - mongo
      
  user_api:
    build: 
      context: .
      dockerfile: ./user/cmd/api/Dockerfile
    container_name: user_api_container
    networks:
      - app-tier
    image: user_api:v1
    restart: always
    expose:
      - "8889"
    depends_on:
      - user_rpc
      - teacher_rpc
    
  excel_api:
    build: 
      context: .
      dockerfile: ./excel/cmd/api/Dockerfile
    container_name: excel_api_container
    networks:
      - app-tier
    image: excel_api:v1
    restart: always
    expose:
      - "9002"
    depends_on:
      - student_rpc
      - teacher_rpc
      - classroom_rpc

  schedule_api:
    build: 
      context: .
      dockerfile: ./schedule/cmd/api/Dockerfile
    container_name: schedule_api_container
    networks:
      - app-tier
    image: schedule_api:v1
    restart: always
    expose:
      - "8892"
    depends_on:
      - student_rpc
      - classroom_rpc
      - teacher_rpc
      - mongo

  teacher_api:
    build: 
      context: .
      dockerfile: ./teacher/cmd/api/Dockerfile
    container_name: teacher_api_container
    networks:
      - app-tier
    image: teacher_api:v1
    restart: always
    expose:
      - "8893"
    depends_on:
      - teacher_rpc
  
  classroom_api:
    build: 
      context: .
      dockerfile: ./classroom/cmd/api/Dockerfile
    container_name: classroom_api_container
    networks:
      - app-tier
    image: classroom_api:v1
    restart: always
    expose:
      - "8894"
    depends_on:
      - classroom_rpc

  student_api:
    build: 
      context: .
      dockerfile: ./student/cmd/api/Dockerfile
    container_name: student_api_container
    networks:
      - app-tier
    image: student_api:v1
    restart: always
    expose:
      - "8895"
    depends_on:
      - student_rpc

  nginx-gateway:
    image: nginx:1.21.5
    container_name: nginx-gateway
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8888:8081
    volumes:
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/log:/var/log/nginx
    networks:
      - app-tier