// Code generated by goctl. DO NOT EDIT.
package types

type Student struct {
	Id            string   `json:"id"`
	Name          string   `json:"name"`
	PaperKeywords []string `json:"paper_keywords"`
	PaperTitle    string   `json:"paper_title"`
	GroupId       string   `json:"group_id"`
	Mentor        string   `json:"mentor"`
}

type QueryStudentsReply struct {
	Students []Student `json:"students"`
}

type RemoveStudentReq struct {
	Id string `path:"id"`
}
