// Code generated by goctl. DO NOT EDIT.
package types

type Student struct {
	Id            string   `json:"id"`
	Name          string   `json:"name"`
	PaperKeywords []string `json:"paper_keywords"`
	PaperTitle    string   `json:"paper_title"`
	GroupId       string   `json:"group_id"`
	Mentor        string   `json:"mentor"`
}

type QueryStudentsReply struct {
	Students []Student `json:"students"`
}

type RemoveStudentReq struct {
	Id string `path:"id"`
}

type Group struct {
	Id        string   `json:"id"`
	Name      string   `json:"name"`
	DefenseId string   `json:"defense_id"`
	Members   []string `json:"members"`
}

type NewGroupReq struct {
	Name string `path:"name"`
}

type NewGroupResp struct {
	GroupId string `json:"group_id"`
}

type AddMemberReq struct {
	StudentId string `path:"student_id"`
	GroupId   string `path:"group_id"`
}

type RemoveMemberReq struct {
	StudentId string `path:"student_id"`
	GroupId   string `path:"group_id"`
}

type QueryGroupReq struct {
	Id string `path:"id"`
}

type RemoveGroupReq struct {
	Id string `path:"id"`
}

type QueryGroupContentResp struct {
	Keywords []string `json:"keywords"`
	Mentors  []string `json:"mentors"`
}
