FROM golang:alpine AS builder

LABEL stage=gobuilder

ENV CGO_ENABLED 0
ENV GOOS linux
ENV GOPROXY https://goproxy.cn,direct

WORKDIR /build/zero

ADD go.mod .
ADD go.sum .
RUN go mod download
COPY . .
COPY teacher/cmd/rpc/etc /app/etc
RUN go build -ldflags="-s -w" -o /app/teacher teacher/cmd/rpc/teacher.go


FROM alpine

RUN apk update --no-cache && apk add --no-cache ca-certificates tzdata
ENV TZ Asia/Shanghai

WORKDIR /app
COPY --from=builder /app/teacher /app/teacher
COPY --from=builder /app/etc /app/etc

CMD ["./teacher", "-f", "etc/teacher.yaml"]
