// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"TDS-backend/user/cmd/rpc/internal/logic"
	"TDS-backend/user/cmd/rpc/internal/svc"
	"TDS-backend/user/cmd/rpc/types/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetUser(ctx context.Context, in *user.IdRequest) (*user.UserResponse, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *UserServer) GetToken(ctx context.Context, in *user.TokenRequest) (*user.TokenResponse, error) {
	l := logic.NewGetTokenLogic(ctx, s.svcCtx)
	return l.GetToken(in)
}

func (s *UserServer) Register(ctx context.Context, in *user.RegisterRequest) (*user.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) RegisterBatch(ctx context.Context, in *user.RegisterBatchRequest) (*user.RegisterBatchResponse, error) {
	l := logic.NewRegisterBatchLogic(ctx, s.svcCtx)
	return l.RegisterBatch(in)
}

func (s *UserServer) GetTeacherList(ctx context.Context, in *user.GetTeacherListRequest) (*user.GetTeacherListResponse, error) {
	l := logic.NewGetTeacherListLogic(ctx, s.svcCtx)
	return l.GetTeacherList(in)
}

func (s *UserServer) GetTeacher(ctx context.Context, in *user.GetTeacherByIdRequest) (*user.TeacherInfo, error) {
	l := logic.NewGetTeacherLogic(ctx, s.svcCtx)
	return l.GetTeacher(in)
}

func (s *UserServer) SetTeacherInfo(ctx context.Context, in *user.SetTeacherInfoRequest) (*user.SetTeacherInfoResponse, error) {
	l := logic.NewSetTeacherInfoLogic(ctx, s.svcCtx)
	return l.SetTeacherInfo(in)
}
