// Code generated by goctl. DO NOT EDIT.
package types

type TSchedule struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	StartTime string `json:"start_time"`
	EndTime   string `json:"end_time"`
}

type GetTScheduleReq struct {
}

type GetTScheduleReply struct {
	Schedules []TSchedule `json:"schedules"`
}

type SetTScheduleReq struct {
	Schedules []TSchedule `json:"schedules"`
}

type SetTScheduleReply struct {
}

type DSchedule struct {
	Name      string `json:"name"`
	Classroom string `json:"classroom"`
	StartTime string `json:"start_time"`
	EndTime   string `json:"end_time"`
}

type GetDScheduleReq struct {
	Schedules []DSchedule `json:"schedules"`
}

type GetDScheduleReply struct {
	Schedules []DSchedule `json:"schedules"`
}
