// Code generated by goctl. DO NOT EDIT.
package types

type MetaType struct {
	Roles []string `json:"roles"`
}

type RouteMenuReq struct {
	Username string `json:"username"`
}

type RouteMenuItem struct {
	Name      string          `json:"name"`
	Path      string          `json:"path"`
	Component string          `json:"component"`
	Meta      MetaType        `json:"meta"`
	Children  []RouteMenuItem `json:"children,optional"`
}

type RouteMenuReply struct {
	Menu []RouteMenuItem `json:"menu"`
}

type HeaderItem struct {
	Name       string `json:"name"`
	RouterName string `json:"routername"`
}

type HeaderReply struct {
	Headers []HeaderItem `json:"headers"`
}

type HeaderReq struct {
}
