// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"TDS-backend/classroom/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/classroom/import/excel",
				Handler: ImportClassroomsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/classroom/query/all",
				Handler: QueryAllClassroomsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/classroom/query/:id",
				Handler: QueryClassroomHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/classroom/remove/:id",
				Handler: RemoveClassroomHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
