// Code generated by goctl. DO NOT EDIT.
package types

type Schedule struct {
	ScheduleId string `json:"schedule_id,optional"`
	Name       string `json:"name"`
	StartTime  string `json:"start_time"`
	EndTime    string `json:"end_time"`
}

type Defense struct {
	DefenseId string `json:"defense_id"`
	StartTime string `json:"start_time"`
	EndTime   string `json:"end_time"`
}

type Teacher struct {
	Id                string     `json:"id,optional"`
	Name              string     `json:"name,optional"`
	MaxDefensePerWeek int        `json:"max_defense_per_week,optional"`
	PreferKeywords    []string   `json:"prefer_keywords,optional"`
	Schedules         []Schedule `json:"schedules,optional"`
	Defenses          []Defense  `json:"defenses,optional"`
}

type QueryTeacherReq struct {
	Id string `path:"id"`
}

type QueryTeachersReq struct {
	Teachers []Teacher `json:"teachers"`
}

type ModifyTeacherReq struct {
	Id         string  `json:"id"`
	NewTeacher Teacher `json:"new_teacher"`
}
