// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"TDS-backend/schedule/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/query/scholar/:id",
				Handler: queryDefenseTeacherStudentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/query/id/:id",
				Handler: queryDefenseHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/query/all",
				Handler: queryAllDefenseHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: addDefenseHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/modify",
				Handler: ModifyDefenseHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/remove",
				Handler: RemoveDefenseHandler(serverCtx),
			},
		},
		rest.WithPrefix("/defense"),
	)
}
