// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"TDS-backend/schedule/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/schedule/teacher/query",
				Handler: queryteacherscheduleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/schedule/teacher/set",
				Handler: setteacherscheduleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/schedule/defense/query",
				Handler: querydefensescheduleHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
