// Code generated by goctl. DO NOT EDIT!
// Source: excel.proto

package server

import (
	"TDS-backend/excel/cmd/rpc/internal/logic"
	"TDS-backend/excel/cmd/rpc/internal/svc"
	"TDS-backend/excel/cmd/rpc/types/excel"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	excel.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) ParseExcel(stream excel.User_ParseExcelServer) error {
	l := logic.NewParseExcelLogic(stream.Context(), s.svcCtx)
	return l.ParseExcel(stream)
}
