// Code generated by goctl. DO NOT EDIT.
package types

type Defense struct {
	DefenseId string `json:"defense_id"`
	StartTime string `json:"start_time"`
	EndTime   string `json:"end_time"`
}

type Classroom struct {
	ID        string    `json:"id,optional"`
	Location  string    `json:"location"`
	Name      string    `json:"name"`
	StartTime string    `json:"start_time"`
	EndTime   string    `json:"end_time"`
	Defenses  []Defense `json:"defenses,optional"`
}

type QueryClassroomReq struct {
	Id string `path:"id"`
}

type QueryClassroomsReply struct {
	Classrooms []Classroom `json:"classrooms"`
}

type RemoveClassroomReq struct {
	Id string `path:"id"`
}
