// Code generated by goctl. DO NOT EDIT.
package types

type Classroom struct {
	ID        string `json:"id,optional"`
	Location  string `json:"location"`
	Name      string `json:"name"`
	StartTime string `json:"start_time"`
	EndTime   string `json:"end_time"`
}

type QueryClassroomReq struct {
	Id string `path:"id"`
}

type QueryClassroomsReply struct {
	Classrooms []Classroom `json:"classrooms"`
}

type RemoveClassroomReq struct {
	Id string `path:"id"`
}
