// Code generated by goctl. DO NOT EDIT.
package types

type ImportExcelReq struct {
	Usage string `path:"usage"`
}

type ImportExcelReply struct {
	Count int `json:"count"`
}

type PreviewExcelReply struct {
	Data [][]string `json:"data"`
}
