// Code generated by goctl. DO NOT EDIT!
// Source: excel.proto

package user

import (
	"context"

	"TDS-backend/excel/cmd/rpc/types/excel"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ExcelInfo     = excel.ExcelInfo
	ExcelRequest  = excel.ExcelRequest
	ExcelResponse = excel.ExcelResponse
	RowInfo       = excel.RowInfo

	User interface {
		ParseExcel(ctx context.Context, opts ...grpc.CallOption) (excel.User_ParseExcelClient, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) ParseExcel(ctx context.Context, opts ...grpc.CallOption) (excel.User_ParseExcelClient, error) {
	client := excel.NewUserClient(m.cli.Conn())
	return client.ParseExcel(ctx, opts...)
}
