// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"TDS-backend/excel/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/excel/import/:usage",
				Handler: ImportHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/excel/preview",
				Handler: PreviewHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/excel/export/:usage",
				Handler: ExportHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
