// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"TDS-backend/user/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: loginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: registerHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/teacher/getlist",
				Handler: getteacherlistHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/teacher/set/info",
				Handler: setteacherinfoHandler(serverCtx),
			},
		},
	)
}
