// Code generated by goctl. DO NOT EDIT!
// Source: student.proto

package server

import (
	"context"

	"TDS-backend/student/cmd/rpc/internal/logic"
	"TDS-backend/student/cmd/rpc/internal/svc"
	"TDS-backend/student/cmd/rpc/types/student"
)

type StudentServiceServer struct {
	svcCtx *svc.ServiceContext
	student.UnimplementedStudentServiceServer
}

func NewStudentServiceServer(svcCtx *svc.ServiceContext) *StudentServiceServer {
	return &StudentServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *StudentServiceServer) AddStudent(ctx context.Context, in *student.AddStudentRequest) (*student.EmptyResponse, error) {
	l := logic.NewAddStudentLogic(ctx, s.svcCtx)
	return l.AddStudent(in)
}

func (s *StudentServiceServer) RemoveStudent(ctx context.Context, in *student.RemoveStudentRequest) (*student.EmptyResponse, error) {
	l := logic.NewRemoveStudentLogic(ctx, s.svcCtx)
	return l.RemoveStudent(in)
}

func (s *StudentServiceServer) ModifyStudent(ctx context.Context, in *student.ModifyStudentRequest) (*student.EmptyResponse, error) {
	l := logic.NewModifyStudentLogic(ctx, s.svcCtx)
	return l.ModifyStudent(in)
}

func (s *StudentServiceServer) QueryAllStudents(ctx context.Context, in *student.EmptyRequest) (*student.QueryStudentsResponse, error) {
	l := logic.NewQueryAllStudentsLogic(ctx, s.svcCtx)
	return l.QueryAllStudents(in)
}

func (s *StudentServiceServer) QueryStudent(ctx context.Context, in *student.QueryStudentRequest) (*student.QueryStudentResponse, error) {
	l := logic.NewQueryStudentLogic(ctx, s.svcCtx)
	return l.QueryStudent(in)
}

func (s *StudentServiceServer) QueryNondefensedStudents(ctx context.Context, in *student.EmptyRequest) (*student.QueryStudentsResponse, error) {
	l := logic.NewQueryNondefensedStudentsLogic(ctx, s.svcCtx)
	return l.QueryNondefensedStudents(in)
}

func (s *StudentServiceServer) QueryStudentsBatch(ctx context.Context, in *student.QueryStudentsBatchRequest) (*student.QueryStudentsResponse, error) {
	l := logic.NewQueryStudentsBatchLogic(ctx, s.svcCtx)
	return l.QueryStudentsBatch(in)
}
